name: Core

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: set up NDK r21
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21
        add-to-path: true
    - name: Build
      run: |
        mkdir -p /home/runner/work/Riru-ClipboardWhitelist/Riru-ClipboardWhitelist
        NDK_VER="$( find "$ANDROID_NDK_HOME" -regextype egrep -iregex '.*[^0-9.]2[12]\.[0-9][^/]*$' | head -1 )"
        NDK_DIR="$ANDROID_NDK_HOME"
        NDK_ROOT="$ANDROID_NDK_HOME"
        ANDROID_NDK_LATEST_HOME="$ANDROID_NDK_HOME"
        export NDK_VER NDK_DIR NDK_ROOT ANDROID_NDK_HOME ANDROID_NDK_LATEST_HOME
        cur="${PWD}"; cur="${cur: 1}"; cur="${cur%%/*}"; base="/$cur";
        find "$base/" /usr/local/ /opt/ -xdev -noleaf -regextype egrep \
             -iregex '.*(android|gradle|ndk).*' -type f \
             -exec grep -Elwe '21\.[0-9]\.[0-9]{4,}' -- {} + \
          | xargs -d $'\n' sed -s -r \
              -e ':a s~(^|[^0-9.])(21\.[0-9]\.[0-9]{4,})($|[^0-9.])~\1'"$NDK_VER"'\3~g; ta; ' \
              -i;
        echo $'\r\n'"ndk.dir=$ANDROID_NDK_HOME" >> local.properties
        echo $'\r\n'"android.ndkVersion=$NDK_VER" >> local.properties
        echo $'\r\n'"ndk.dir=$ANDROID_NDK_HOME"$'\r\n'ndk.ver=$NDK_VER"$'\r\n'ndk.version=$NDK_VER"$'\r\n'android.ndk.dir=$ANDROID_NDK_HOME"$'\r\n'android.ndk.version=$NDK_VER"$'\r\n' | tee -a  /home/runner/work/Riru-ClipboardWhitelist/Riru-ClipboardWhitelist/gradle.properties >> local.properties
        echo $'\r\nstorePassword=changeit\r\nkeyPassword=changeit\r\nkeyAlias=testkey\r\nstoreFile='"$( find "$JAVA_HOME" -name security | head -1 )"$'/jssecerts'$'\r\n' > /home/runner/work/Riru-ClipboardWhitelist/Riru-ClipboardWhitelist/keystore.properties
        echo $'\norg.gradle.caching=false' >> gradle.properties
        echo $'\norg.gradle.parallel=false' >> gradle.properties
        echo $'\norg.gradle.vfs.watch=false' >> gradle.properties
        echo $'\norg.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew --stacktrace \
           || ./gradlew --stacktrace build \
           || ./gradlew --stacktrace configure \
           || ./gradlew --stacktrace app \
           || ./gradlew --stacktrace -k --ignore-errors \
           || find $( pwd ) -name "*.gradle" -exec bash -c \
              'for f in "$@"; do fn="${f##*/}"; dir="${f: 0:${#f}-${#fn}}"; dir="${dir%%/}"; cd "$dir" || continue; echo "*** ENTERED DIR: $dir ***"; gradle build || gradlew build || '"$PWD"'/gradlew build; echo $?; done' -- "{}" + \
              ;
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        ANDROID_NDK_LATEST_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mappings
        path: |
          core/build/outputs/*
