name: Core

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up NDK r23
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23
        add-to-path: true
    - name: Build gradle
      run: |
        set -x +e
        mkdir -p "$GITHUB_WORKSPACE"
        export SIGNING_STORE_DIR="$RUNNER_TEMP/keystore"
        export SIGNING_STORE_FILE="SIGNING_STORE_DIR/example.com.jks"
        export SIGNING_STORE_PASSWORD="changeit"
        mkdir -p "$SIGNING_STORE_DIR"
        export SIGNING_KEY_ALIAS="example.com"
        export SIGNING_KEY_DNAME="CN=$SIGNING_KEY_ALIAS, OU=Example Org, O=Example Company, L=San Francisco, ST=California, C=US"
        export SIGNING_KEY_PASSWORD="changeit"
        export ANDROID_NDK_LATEST_HOME="$ANDROID_NDK_HOME"
        export KEYSTORE="$SIGNING_STORE_FILE"
        export NDK_DIR="$ANDROID_NDK_HOME"
        export NDK_ROOT="$ANDROID_NDK_HOME"
        export NDK_VER="23.0.7123448"
        CRLF=$'\r\n'
        
        keytool -genkeypair -v \
              -alias       "$SIGNING_KEY_ALIAS" \
              -dname       "$SIGNING_KEY_DNAME" \
              -keystore    "$SIGNING_STORE_FILE" \
              -keypass:env   SIGNING_KEY_PASSWORD \
              -storepass:env SIGNING_STORE_PASSWORD \
              -keyalg EC -keysize 256 -validity 385
        echo "$SIGNING_STORE_PASSWORD$CRLF" \
          | keytool -keystore "$KEYSTORE" \
              -keypass:env    SIGNING_KEY_PASSWORD \
              -storepass:env  SIGNING_STORE_PASSWORD \
              -importkeystore \
              -srckeystore  "$SIGNING_STORE_FILE" \
              -destkeystore "$SIGNING_STORE_FILE" \
              -deststoretype pkcs12
        {
          echo "storeFile=$$SIGNING_STORE_FILE";
          echo "storePassword=$SIGNING_STORE_PASSWORD";
          echo "keyAlias=$SIGNING_KEY_ALIAS";
          echo "keyPassword=$SIGNING_KEY_PASSWORD";
        } | tee keystore.properties \
          ;
        {
          echo "android.ndkVersion=$NDK_VER";
          echo "Pkg.Revision=$NDK_VER";
          evho "Pkg.Name=android.ndk";
        } | tee -a "$ANDROID_NDK_HOME/source.properties"\
          | tee -a "$ANDROID_NDK_ROOT/source.properties"\
          | tee -a "local.properties" \
          ;
        # // echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
        echo "android.ndkVersion=$NDK_VER" \
          | tee -a local.properties
        # // echo $'\r\n'"ndk.dir=$ANDROID_NDK_HOME"$'\r\n'ndk.ver=$NDK_VER"$'\r\n'ndk.version=$NDK_VER"$'\r\n'android.ndk.dir=$ANDROID_NDK_HOME"$'\r\n'android.ndk.version=$NDK_VER"$'\r\n' | tee -a  $GITHUB_WORKSPACE/gradle.properties >> local.properties
        {
          echo "org.gradle.caching=true";
          echo "org.gradle.parallel=true";
          echo "org.gradle.vfs.watch=false";
          echo "org.gradle.jvmargs=-Xmx2048m";
        } | tee -a gradle.properties
        grep -Ehsre 'mavenCentral\(\)' --include="build.gradle.kts" -l -- "." | xargs -d $'\n' grep -Fhse 'uri("https://mvnrepository.com/artifact")' -L -- | xargs -d $'\n' sed -s -r -e '1h;1!H;$!d;x; \~uri\("https://mvnrepository.com/artifact/?"\)~bdone; :a s~\n([\t ]*)(mavenCentral\(\))~\n\1xx\2\n\1maven {\n\1    url = uri("https://mvnrepository.com/artifact")\n\1}~; ta; s~xx(mavenCentral|google)~\1~g; :done ' -i --
        typeset -p -x
        ./gradlew module:assembleRelease
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: |
          ./*
          build
          build/*
          build/**
          buildRelease
          buildRelease/*
          buildRelease/**
          module
          module/*
          module/**
          $GITHUB_WORKSPACE/**